symbol_weights:
  S1: 200
  S2: 180
  S3: 160
  S4: 140
  S5: 100
  S6: 60
  S7: 30
  S8: 10
  B: 5
  W: 0

wild_chance_on_reel_2_3_4: 0.06

free_spins_by_scatter:
  3: 10
  4: 15
  5: 20

payout_table:
  S1:
    3: 25
    4: 150
    5: 450
  S2:
    3: 25
    4: 150
    5: 450
  S3:
    3: 25
    4: 150
    5: 450
  S4:
    3: 25
    4: 150
    5: 450
  S5:
    3: 75
    4: 250
    5: 1000
  S6:
    3: 125
    4: 500
    5: 2500
  S7:
    3: 125
    4: 500
    5: 2500
  S8:
    2: 50
    3: 250
    4: 1250
    5: 12500
  B:
    3: 100
    4: 500
    5: 2500
